### ISSUE TITLE
Disallow custom Kubeflow notebook images

### ISSUE THREAD

**Issue by brendangadd** [StatCan/terraform-kubernetes-aks-platform-daaas#1]
Kubeflow Notebooks allows the user to reference a custom image for the notebook server. It should be limited to the predefined list – including any images we add ourselves.

**Comment by frazs** [comment]
I believe this could be done by setting readOnly to true in spawnerFormDefaults on our instance of [these settings](https://github.com/kubeflow/kubeflow/blob/master/components/jupyter-web-app/backend/kubeflow_jupyter/common/yaml/spawner_ui_config.yaml).

However, I am not sure where to apply any such configuration changes for our instance.

We would also want to limit this to a quick test until the predefined images we want are determined, and they seem to be defined in the same configuration file.

**Comment by blairdrummond** [comment]
@sylus @zachomedia I believe this can be closed?

**Comment by sylus** [comment]
Yup OPA is now in place!
