### ISSUE TITLE
torch tools

### ISSUE THREAD

**Issue by chritter** [StatCan/terraform-kubernetes-aks-platform-daaas#10]
Hello,

Could you add torchvision and torchtext packages to the base image?

Thank you.

**Comment by blairdrummond** [comment]
@sylus This can be closed.

**Comment by sylus** [comment]
I had to remove these as were failing the build think was in pytorch channel?

**Comment by sylus** [comment]
Can we move this over to https://github.com/statcan/kubeflow-containers
