### ISSUE TITLE
Request for Kubeflow Notebooks: PyTorch, Geomatics, XGBoost

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/terraform-kubernetes-aks-platform-daaas#3]
I have had requests from my team for the following pre-built images:

**Python**:
1. PyTorch
2. Geomatics: mostly gdal + rasterio
3. XGBoost

**R**:
1. https://hub.docker.com/r/rocker/geospatial

**Comment by blairdrummond** [comment]
What are the reuqirements for a base image to work with Kubeflow?

**Comment by chritter** [comment]
@blairdrummond Its a good idea to group some of the specialized packages.

**Comment by szinck1** [comment]
> 
> 
> What are the reuqirements for a base image to work with Kubeflow?

@blairdrummond See this link:
https://www.kubeflow.org/docs/notebooks/custom-notebook/
