### ISSUE TITLE
jupyter lab extensions

### ISSUE THREAD

**Issue by chritter** [StatCan/terraform-kubernetes-aks-platform-daaas#6]
Hello,
I would like to request the following extensions for Jupyter lab

* ttps://github.com/jupyterlab/jupyterlab-git
*  https://github.com/ijmbarr/jupyterlab_spellchecker
*  https://github.com/jupyterlab/jupyterlab-latex
*  https://github.com/ian-r-rose/jupyterlab-toc
*  https://github.com/aquirdTurtle/Collapsible_Headings
* https://github.com/krassowski/jupyterlab-go-to-definition
*  https://github.com/ryantam626/jupyterlab_code_formatter
*  https://github.com/krassowski/jupyterlab-lsp
*  https://github.com/bokeh/jupyter_bokeh
* https://github.com/jupyter-widgets/ipywidgets
*  https://github.com/jupyterlab/jupyter-renderers
*  https://github.com/plotly/jupyterlab-dash
*  https://awesomeopensource.com/project/lckr/jupyterlab-variableInspector
*  https://awesomeopensource.com/project/chaoleili/jupyterlab_tensorboard
*  https://awesomeopensource.com/project/matplotlib/ipympl

Thank you.

**Comment by blairdrummond** [comment]
Merging your other issue with this one.

Will add
https://ndres.me/post/best-jupyter-notebook-extensions/

**Comment by blairdrummond** [comment]
@sylus @chritter I think this can be closed. Most of these have been added. Some were skipped because of version incompatibilities.

FYI, future issues can go here https://github.com/StatCan/kubeflow-containers
